-- Descrições da planilha do Ivan (as do SisChef), carga de 08/10/2026 — cada palavra delas vira palavra-chave da sugestão do cupom.
-- Só ATUALIZA a coluna `descricao` de produtos que já estão em produto_planilha; não cria produto e não mexe na unidade.
-- Os produtos que já estão em itens_semana continuam com o nome de lá na lista; a descrição só alimenta a busca por palavras.
begin;
update produto_planilha set descricao = 'ABACATE - INSUMOS (KG)' where produto_id = 3469827;
update produto_planilha set descricao = 'AÇÚCAR CRISTAL - INSUMOS (KG)' where produto_id = 1874466;
update produto_planilha set descricao = 'AÇÚCAR MASCAVO - INSUMOS (KG)' where produto_id = 3138634;
update produto_planilha set descricao = 'AÇÚCAR REFINADO - INSUMOS (KG)' where produto_id = 3139124;
update produto_planilha set descricao = 'ÁGUA COM GÁS 500ML' where produto_id = 1836958;
update produto_planilha set descricao = 'ÁGUA SEM GÁS 500ML' where produto_id = 1836957;
update produto_planilha set descricao = 'ÁGUA TÔNICA 350ML' where produto_id = 2521405;
update produto_planilha set descricao = 'ALECRIN - INSUMOS (KG)' where produto_id = 3476494;
update produto_planilha set descricao = 'ALFACE - INSUMOS (KG)' where produto_id = 3469718;
update produto_planilha set descricao = 'ALGA NORI - INSUMOS (UN)' where produto_id = 3484936;
update produto_planilha set descricao = 'ALHO COMUM DESCASCADO - INSUMOS (KG)' where produto_id = 3469574;
update produto_planilha set descricao = 'AMENDOIN XEREM - INSUMOS (KG)' where produto_id = 3476354;
update produto_planilha set descricao = 'AMIDO DE MILHO - INSUMOS (KG)' where produto_id = 1855901;
update produto_planilha set descricao = 'ARROZ JAPONÊS - INSUMOS (KG)' where produto_id = 3484937;
update produto_planilha set descricao = 'ARROZ PARBOLIZADO - INSUMOS (KG)' where produto_id = 3613531;
update produto_planilha set descricao = 'AZEITE EXTRA VIRGEM - INSUMOS (KG)' where produto_id = 3659811;
update produto_planilha set descricao = 'AZEITONA VERDE FATIADA - INSUMOS (KG)' where produto_id = 3476496;
update produto_planilha set descricao = 'BACON EM CUBOS - INSUMOS (KG)' where produto_id = 3469722;
update produto_planilha set descricao = 'BACON FATIADO - INSUMOS (KG)' where produto_id = 3469723;
update produto_planilha set descricao = 'BAF-10 - INSUMOS (KG)' where produto_id = 3469582;
update produto_planilha set descricao = 'BANANA - INSUMOS (KG)' where produto_id = 1838999;
update produto_planilha set descricao = 'BANHA DE PORCO - INSUMOS (KG)' where produto_id = 3469725;
update produto_planilha set descricao = 'BARAM - INSUMOS (UN)' where produto_id = 3484938;
update produto_planilha set descricao = 'BASE SWEET - INSUMOS (KG)' where produto_id = 3469585;
update produto_planilha set descricao = 'BATATA CRINKLE - INSUMOS (KG)' where produto_id = 3469726;
update produto_planilha set descricao = 'BISCOITO OREO - INSUMOS (KG)' where produto_id = 1855890;
update produto_planilha set descricao = 'BLEND 160G - INSUMOS (KG)' where produto_id = 3478978;
update produto_planilha set descricao = 'BLEND SMASH 90G - INSUMOS (KG)' where produto_id = 3587410;
update produto_planilha set descricao = 'BRÓCOLIS - UND - INSUMOS (KG)' where produto_id = 3484939;
update produto_planilha set descricao = 'CALABRESA RETA - INSUMOS (KG)' where produto_id = 3454438;
update produto_planilha set descricao = 'CALDO DE CARNE - INSUMO (KG)' where produto_id = 3469696;
update produto_planilha set descricao = 'CALDO DE GALINHA - INSUMOS (KG)' where produto_id = 3469586;
update produto_planilha set descricao = 'CAMARÃO 34/40 - INSUMO (KG)' where produto_id = 3469588;
update produto_planilha set descricao = 'CAMARÃO 51/60 - INSUMO (KG)' where produto_id = 3484954;
update produto_planilha set descricao = 'CANELA EM PÓ - INSUMOS (KG)' where produto_id = 3506391;
update produto_planilha set descricao = 'CANUDO P/ MILK SHAKE - INSUMO (UN)' where produto_id = 3836906;
update produto_planilha set descricao = 'CARNE CABEÇA DE LOMBO - INSUMOS (KG)' where produto_id = 3484955;
update produto_planilha set descricao = 'CARNE FILÉ - INSUMOS' where produto_id = 3882028;
update produto_planilha set descricao = 'CARNE LAGARTO - INSUMOS (KG)' where produto_id = 3469590;
update produto_planilha set descricao = 'CARNE PICANHA - INSUMOS (KG)' where produto_id = 3469593;
update produto_planilha set descricao = 'CARNE SECA DE SOL - INSUMOS (KG)' where produto_id = 3469600;
update produto_planilha set descricao = 'CASTANHA CAJU XEREM - INSUMOS (KG)' where produto_id = 3474953;
update produto_planilha set descricao = 'CEBOLA BRANCA - INSUMOS (KG)' where produto_id = 3138632;
update produto_planilha set descricao = 'CEBOLA EM PÓ - INSUMOS (KG)' where produto_id = 3469595;
update produto_planilha set descricao = 'CEBOLA ROXA - INSUMOS (KG)' where produto_id = 3469735;
update produto_planilha set descricao = 'CEBOLINHA - INSUMOS (KG)' where produto_id = 3469737;
update produto_planilha set descricao = 'CENOURA - UND -INSUMOS (KG)' where produto_id = 3484959;
update produto_planilha set descricao = 'CHAMPIGNON FATIADO - INSUMOS (KG)' where produto_id = 3659815;
update produto_planilha set descricao = 'CHEDDAR FATIADO - INSUMOS (KG)' where produto_id = 3138560;
update produto_planilha set descricao = 'CHEIRO VERDE - INSUMOS (KG)' where produto_id = 3469601;
update produto_planilha set descricao = 'CHOCO POWER MACRO - INSUMOS (KG)' where produto_id = 3476368;
update produto_planilha set descricao = 'CHOCOTINE - INSUMOS (KG)' where produto_id = 3543752;
update produto_planilha set descricao = 'COBERTURA CARAMELO - INSUMOS (KG)' where produto_id = 3476369;
update produto_planilha set descricao = 'COBERTURA CHOCOLATE - INSUMOS (KG)' where produto_id = 3476370;
update produto_planilha set descricao = 'COBERTURA DOCE DE LEITE - INSUMOS (KG)' where produto_id = 3476501;
update produto_planilha set descricao = 'COBERTURA MORANGO - INSUMOS (KG)' where produto_id = 3634150;
update produto_planilha set descricao = 'COCA COLA S/ AÇÚCAR 350 ML' where produto_id = 1836984;
update produto_planilha set descricao = 'COCA COLA 1L' where produto_id = 1836992;
update produto_planilha set descricao = 'COCA COLA 2L' where produto_id = 1836997;
update produto_planilha set descricao = 'COCA COLA 350 ML' where produto_id = 1836982;
update produto_planilha set descricao = 'COCA COLA KS 290ML' where produto_id = 2485719;
update produto_planilha set descricao = 'COCA COLA S/ AÇÚCAR 1L' where produto_id = 2952974;
update produto_planilha set descricao = 'COCA COLA S/ AÇÚCAR 2L' where produto_id = 2952976;
update produto_planilha set descricao = 'COCA COLA S/ AÇÚCAR KS 290ML' where produto_id = 2485724;
update produto_planilha set descricao = 'COLHER DESC. GELATO - INSUMO (UN)' where produto_id = 3836996;
update produto_planilha set descricao = 'COPO PP PERSONALIZADO 330ML - INSUMO (UN)' where produto_id = 3836897;
update produto_planilha set descricao = 'CORANTE VERMELHO - INSUMOS (KG)' where produto_id = 3469603;
update produto_planilha set descricao = 'COUVE - INSUMOS (KG)' where produto_id = 3484963;
update produto_planilha set descricao = 'COXA DA ASA - INSUMOS (KG)' where produto_id = 3469604;
update produto_planilha set descricao = 'CREME DE AVELÃ - INSUMOS (KG)' where produto_id = 3469607;
update produto_planilha set descricao = 'CREME DE LEITE - INSUMOS (KG)' where produto_id = 1855900;
update produto_planilha set descricao = 'CUMINHO - INSUMOS (KG)' where produto_id = 3469613;
update produto_planilha set descricao = 'DISQUETE CHOCOLATE - INSUMOS (KG)' where produto_id = 3476408;
update produto_planilha set descricao = 'DORITOS SALGADINHO - INSUMOS (KG)' where produto_id = 3572108;
update produto_planilha set descricao = 'ERVILHA CONGELADA - INSUMOS (KG)' where produto_id = 3476505;
update produto_planilha set descricao = 'EXTRATO DE TOMATE CONCENTRADO - INSUMOS (KG)' where produto_id = 3476506;
update produto_planilha set descricao = 'FANTA LARANJA 350 ML' where produto_id = 2722189;
update produto_planilha set descricao = 'FANTA LARANJA KS 290ML' where produto_id = 2846224;
update produto_planilha set descricao = 'FARINHA DE SÊMOLA - INSUMOS (KG)' where produto_id = 3138796;
update produto_planilha set descricao = 'FARINHA DE TRIGO INTEGRAL - INSUMOS (KG)' where produto_id = 3138795;
update produto_planilha set descricao = 'FARINHA LACTA - INSUMOS (KG)' where produto_id = 3476411;
update produto_planilha set descricao = 'FARINHA PANKO - INSUMOS (KG)' where produto_id = 3469619;
update produto_planilha set descricao = 'FARINHA TRIGO LONGA FERMENTAÇÃO - INSUMOS (KG)' where produto_id = 3138798;
update produto_planilha set descricao = 'FERMENTO SECO - INSUMOS (KG)' where produto_id = 1857481;
update produto_planilha set descricao = 'FILÉ PEITO DE FRANGO - INSUMOS (KG)' where produto_id = 3573459;
update produto_planilha set descricao = 'FLOCOS DE ARROZ - INSUMOS (KG)' where produto_id = 3476416;
update produto_planilha set descricao = 'FRANGO DESFIADO - INSUMOS (KG)' where produto_id = 3469621;
update produto_planilha set descricao = 'GARRAFA DE SUCO 300ML - INSUMO (UN)' where produto_id = 3837137;
update produto_planilha set descricao = 'GÁS P/ CHANTILLY - INSUMOS (UN)' where produto_id = 3476417;
update produto_planilha set descricao = 'GAS P13 - INSUMOS (UN)' where produto_id = 3469622;
update produto_planilha set descricao = 'GAS P45 - INSUMOS (UN)' where produto_id = 3499754;
update produto_planilha set descricao = 'GELO ESCAMA - INSUMOS (SC)' where produto_id = 3513562;
update produto_planilha set descricao = 'GENGIBRE FATIADO - INSUMOS (KG)' where produto_id = 3484965;
update produto_planilha set descricao = 'GERGELIM MIX - INSUMOS (KG)' where produto_id = 3501747;
update produto_planilha set descricao = 'GLUCOSE EM PÓ - INSUMOS (KG)' where produto_id = 3476450;
update produto_planilha set descricao = 'GOIABADA - INSUMOS (KG)' where produto_id = 3484967;
update produto_planilha set descricao = 'GRANOLA TRADICIONAL - INSUMOS (KG)' where produto_id = 3476422;
update produto_planilha set descricao = 'GUARANÁ AMAZÔNIA KS 290ML' where produto_id = 2485726;
update produto_planilha set descricao = 'GUARANÁ ANTARCTICA 1L' where produto_id = 1836993;
update produto_planilha set descricao = 'GUARANÁ ANTARCTICA 2L' where produto_id = 1836998;
update produto_planilha set descricao = 'GUARANÁ ANTARCTICA 350ML' where produto_id = 1836986;
update produto_planilha set descricao = 'GUARANÁ ANTARCTICA S/ AÇÚCAR 1L' where produto_id = 3713133;
update produto_planilha set descricao = 'GUARANÁ ANTARCTICA S/ AÇÚCAR 350ML' where produto_id = 3324211;
update produto_planilha set descricao = 'GUIOZA CARNE BOVINA - INSUMO (KG)' where produto_id = 3726403;
update produto_planilha set descricao = 'GUIOZA CARNE SUINA - INSUMO (KG)' where produto_id = 3659968;
update produto_planilha set descricao = 'HAMBURGUER VEGETARIANO 110G - INSUMOS (KG)' where produto_id = 3496935;
update produto_planilha set descricao = 'HONDASHI - INSUMO (KG)' where produto_id = 3484972;
update produto_planilha set descricao = 'IOGURTE NATURAL - INSUMOS (KG)' where produto_id = 1855909;
update produto_planilha set descricao = 'KANI - INSUMOS (KG)' where produto_id = 3484973;
update produto_planilha set descricao = 'KETCHUP - INSUMOS (KG)' where produto_id = 3476460;
update produto_planilha set descricao = 'KETCHUP SACHE - INSUMOS (UN)' where produto_id = 3469734;
update produto_planilha set descricao = 'KIT KAT CHOCOLATE - INSUMOS (KG)' where produto_id = 3476428;
update produto_planilha set descricao = 'KIWI - INSUMOS (KG)' where produto_id = 1855915;
update produto_planilha set descricao = 'LÂMPADA LED HP 30W KIAN - INSUMOS (UN)' where produto_id = 3499146;
update produto_planilha set descricao = 'LÂMPADA LED KINA LED 50W BV - INSUMOS (UN)' where produto_id = 3499150;
update produto_planilha set descricao = 'LEITE CONDENSADO - INSUMOS (KG)' where produto_id = 3469626;
update produto_planilha set descricao = 'LEITE EM PÓ INTEGRAL - INSUMOS (KG)' where produto_id = 3469628;
update produto_planilha set descricao = 'LEITE LIQUIDO INTEGRAL - INSUMOS (KG)' where produto_id = 3469635;
update produto_planilha set descricao = 'LEITE NINHO PÓ INTEGRAL - INSUMOS (KG)' where produto_id = 1855881;
update produto_planilha set descricao = 'LEMON PEPPER - INSUMOS (KG)' where produto_id = 3469638;
update produto_planilha set descricao = 'LIMÃO - INSUMOS (KG)' where produto_id = 3469643;
update produto_planilha set descricao = 'LIMÃO SICILIANO - INSUMOS (KG)' where produto_id = 3484974;
update produto_planilha set descricao = 'LOMBO CANADENSE - INSUMOS (KG)' where produto_id = 3476510;
update produto_planilha set descricao = 'MAÇÃ - INSUMOS (KG)' where produto_id = 3469826;
update produto_planilha set descricao = 'MAÇARICO RECARGA - INSUMOS (UN)' where produto_id = 3469745;
update produto_planilha set descricao = 'MACARRÃO ESPAGUETE - INSUMOS (KG)' where produto_id = 3613533;
update produto_planilha set descricao = 'MACARRÃO YAKISSOBA- INSUMOS (KG)' where produto_id = 3484978;
update produto_planilha set descricao = 'MAIONESE MARIANA - INSUMOS (KG)' where produto_id = 3474674;
update produto_planilha set descricao = 'MANGA - INSUMOS (KG)' where produto_id = 3484979;
update produto_planilha set descricao = 'MANJERICÃO - INSUMOS (KG)' where produto_id = 3476511;
update produto_planilha set descricao = 'MARACUJÁ - INSUMOS (KG)' where produto_id = 3531904;
update produto_planilha set descricao = 'MASSA HARUMAKI - INSUMOS (UN)' where produto_id = 3474749;
update produto_planilha set descricao = 'MASSA PARA SOPA - INSUMOS (KG)' where produto_id = 3469646;
update produto_planilha set descricao = 'MAXGEL - INSUMOS (KG)' where produto_id = 3469647;
update produto_planilha set descricao = 'MEGA CREME - INSUMOS (KG)' where produto_id = 3469648;
update produto_planilha set descricao = 'MEL DE ABELHA - INSUMOS (KG)' where produto_id = 3469747;
update produto_planilha set descricao = 'MOLHO AMERICAN CHEESE - INSUMOS (KG)' where produto_id = 3469720;
update produto_planilha set descricao = 'MOLHO BARBECUE - INSUMOS (KG)' where produto_id = 3469751;
update produto_planilha set descricao = 'MOLHO BARBECUE REFIL - INSUMOS (KG)' where produto_id = 3469749;
update produto_planilha set descricao = 'MOLHO CHEDDAR - INSUMOS (KG)' where produto_id = 3454426;
update produto_planilha set descricao = 'MOLHO DE ALHO - INSUMOS (KG)' where produto_id = 3531993;
update produto_planilha set descricao = 'MOLHO DE TOMATE TRADICIONAL- INSUMOS (KG)' where produto_id = 3601627;
update produto_planilha set descricao = 'MOLHO PESTO - INSUMOS (KG)' where produto_id = 3474662;
update produto_planilha set descricao = 'MOLHO SHOYU SACHÊ - INSUMOS (UN)' where produto_id = 3480229;
update produto_planilha set descricao = 'MOLHO TARÊ - INSUMOS (KG)' where produto_id = 3484980;
update produto_planilha set descricao = 'MOLHO TARÊ SACHÊ - INSUMOS (UN)' where produto_id = 3484981;
update produto_planilha set descricao = 'MOLHO TONKATSU - INSUMOS (KG)' where produto_id = 3496931;
update produto_planilha set descricao = 'MOSTARDA - INSUMO (KG)' where produto_id = 3138580;
update produto_planilha set descricao = 'NIKUMAN CALABRESA - INSUMO (KG)' where produto_id = 3484982;
update produto_planilha set descricao = 'NIKUMAN CARNE C/ LEGUMES - INSUMOS (KG)' where produto_id = 3645039;
update produto_planilha set descricao = 'NIKUMAN CARNE SUÍNA - INSUMOS (KG)' where produto_id = 3484984;
update produto_planilha set descricao = 'NIKUMAN FRANGO C/ REQUEIJÃO - INSUMOS (KG)' where produto_id = 3484986;
update produto_planilha set descricao = 'NUGGETS SUPREME - INSUMOS (KG)' where produto_id = 3469754;
update produto_planilha set descricao = 'ÓLEO DE ALGODÃO - INSUMOS (UN)' where produto_id = 3469755;
update produto_planilha set descricao = 'OLEO DE GERGELIM - INSUMOS (KG)' where produto_id = 3496930;
update produto_planilha set descricao = 'ÓLEO DE SOJA - INSUMOS (UN)' where produto_id = 3138573;
update produto_planilha set descricao = 'ORÉGANO - INSUMOS (KG)' where produto_id = 3476519;
update produto_planilha set descricao = 'OVO - INSUMOS (UN)' where produto_id = 3487562;
update produto_planilha set descricao = 'OVOMALTINE EM FLOCOS - INSUMOS (KG)' where produto_id = 3836915;
update produto_planilha set descricao = 'PALMITO RODELAS - INSUMOS (KG)' where produto_id = 3506917;
update produto_planilha set descricao = 'PÃO AUSTRALIANO - INSUMOS (UN)' where produto_id = 3478801;
update produto_planilha set descricao = 'PÃO BRIOCHE - INSUMO (UN)' where produto_id = 3138549;
update produto_planilha set descricao = 'PÁPRICA DEFUMADA - INSUMOS (KG)' where produto_id = 3469651;
update produto_planilha set descricao = 'PÁPRICA DOCE - INSUMOS (KG)' where produto_id = 3469652;
update produto_planilha set descricao = 'PASTA DE ALHO NEGRO - INSUMOS (KG)' where produto_id = 3478968;
update produto_planilha set descricao = 'PASTA SAB. CREME AMERICANO - INSUMOS (KG)' where produto_id = 3469655;
update produto_planilha set descricao = 'PASTA SAB. MORANGO CONCENT. - INSUMOS (KG)' where produto_id = 3663506;
update produto_planilha set descricao = 'PAU DE CANELA - INSUMOS (KG)' where produto_id = 3139126;
update produto_planilha set descricao = 'PEPINO JAPONÊS - INSUMOS (KG)' where produto_id = 3484991;
update produto_planilha set descricao = 'PEPPERONI - INSUMOS (KG)' where produto_id = 3476525;
update produto_planilha set descricao = 'PICLES DE PEPINO - INSUMOS (KG)' where produto_id = 3469761;
update produto_planilha set descricao = 'PIMENTA BIQUINHO - INSUMOS (KG)' where produto_id = 3476526;
update produto_planilha set descricao = 'PIMENTA CALABRESA - INSUMOS (KG)' where produto_id = 3469670;
update produto_planilha set descricao = 'PIMENTA DEDO DE MOÇA - INSUMOS (KG)' where produto_id = 3139125;
update produto_planilha set descricao = 'PIMENTA DO REINO - INSUMOS (KG)' where produto_id = 3469677;
update produto_planilha set descricao = 'PIMENTA SRIRACHA - INSUMOS (KG)' where produto_id = 3469762;
update produto_planilha set descricao = 'PIMENTÃO - INSUMOS (KG)' where produto_id = 3476527;
update produto_planilha set descricao = 'POLPA ACEROLA - INSUMOS (KG)' where produto_id = 3153111;
update produto_planilha set descricao = 'POLPA GOIABA - INSUMOS (KG)' where produto_id = 3153112;
update produto_planilha set descricao = 'POLPA MARACUJA - INSUMOS (KG)' where produto_id = 3153114;
update produto_planilha set descricao = 'POTE ISOPOR DELIVERI 360ML - INSUMO (UN)' where produto_id = 3836960;
update produto_planilha set descricao = 'PRESUNTO - INSUMOS (KG)' where produto_id = 1854714;
update produto_planilha set descricao = 'Q. GORGONZOLA - INSUMOS (KG)' where produto_id = 3474203;
update produto_planilha set descricao = 'Q. MUÇARELA - INSUMOS (KG)' where produto_id = 1854713;
update produto_planilha set descricao = 'Q. PARMESÃO - INSUMOS (KG)' where produto_id = 3476531;
update produto_planilha set descricao = 'Q. PROVOLONE - INSUMOS (KG)' where produto_id = 3476532;
update produto_planilha set descricao = 'QUEIJO COALHO - INSUMOS (KG)' where produto_id = 3474208;
update produto_planilha set descricao = 'QUEIJO MUÇARELA DE BÚFALA - INSUMOS (KG)' where produto_id = 3484992;
update produto_planilha set descricao = 'QUEIJO PRATO FATIADO - INSUMOS (KG)' where produto_id = 3469768;
update produto_planilha set descricao = 'QUEIJO PROVOLONE FATIA - INSUMOS (KG)' where produto_id = 3839640;
update produto_planilha set descricao = 'REFRESCO TANG MORANGO - INSUMOS (UN)' where produto_id = 1855905;
update produto_planilha set descricao = 'REFRIGERANTE H2OH - LIMÃO 500ML' where produto_id = 1836960;
update produto_planilha set descricao = 'REFRIGERANTE H2OH - LIMONETO 500ML' where produto_id = 2074132;
update produto_planilha set descricao = 'REPOLHO BRANCO - INSUMOS (KG)' where produto_id = 3484994;
update produto_planilha set descricao = 'REPOLHO ROXO - INSUMOS (KG)' where produto_id = 3484995;
update produto_planilha set descricao = 'REQ. ALHO PORO - INSUMOS (KG)' where produto_id = 3478804;
update produto_planilha set descricao = 'REQ. CHEDDAR - INSUMOS (KG)' where produto_id = 3454449;
update produto_planilha set descricao = 'REQ. CREAM CHEESE - INSUMOS (KG)' where produto_id = 3469783;
update produto_planilha set descricao = 'REQ. PASTA DE ALHO - INSUMO (KG)' where produto_id = 3656016;
update produto_planilha set descricao = 'REQ. QUATRO QUEIJOS - INSUMOS (KG)' where produto_id = 3476536;
update produto_planilha set descricao = 'REQ. TRADICIONAL - INSUMOS (KG)' where produto_id = 3476537;
update produto_planilha set descricao = 'SABORIZANTE CHOCOLATE SUIÇO - INSUMOS (KG)' where produto_id = 3469679;
update produto_planilha set descricao = 'SABORIZANTE MORANGO - INSUMO (KG)' where produto_id = 3668051;
update produto_planilha set descricao = 'SACO DE PAPEL SPAZIO 2KG - INSUMO (UN)' where produto_id = 3836967;
update produto_planilha set descricao = 'SAL AJI SAL - INSUMOS (KG)' where produto_id = 3469773;
update produto_planilha set descricao = 'SAL COMUM - INSUMO (KG)' where produto_id = 3138591;
update produto_planilha set descricao = 'SALAME FATIADO - INSUMOS (KG)' where produto_id = 3476538;
update produto_planilha set descricao = 'SALMÃO INTEIRO - INSUMOS (KG)' where produto_id = 3484999;
update produto_planilha set descricao = 'SALSICHA HOT DOG - INSUMOS (KG)' where produto_id = 3584909;
update produto_planilha set descricao = 'SAQUE MIRIN - INSUMOS (KG)' where produto_id = 3556701;
update produto_planilha set descricao = 'SCHWEPPES CITRUS' where produto_id = 2471203;
update produto_planilha set descricao = 'SHOYU P/ SUSHI - INSUMOS (KG)' where produto_id = 3485000;
update produto_planilha set descricao = 'SHOYU TRADICIONAL - INSUMOS (KG)' where produto_id = 3644178;
update produto_planilha set descricao = 'SUCO BONBON COM PEDAÇOS DE UVA HAITAI 235ML' where produto_id = 3318570;
update produto_planilha set descricao = 'SUCO DE UVA DEL VALLE 450ML' where produto_id = 1836963;
update produto_planilha set descricao = 'SUCO DEL VALLE NÉCTAR UVA 290ML' where produto_id = 3324209;
update produto_planilha set descricao = 'SUCO REFRESCO LARANJA - INSUMOS (UN)' where produto_id = 3601689;
update produto_planilha set descricao = 'SUCO REFRESCO MORANGO - INSUMOS (UN)' where produto_id = 3601690;
update produto_planilha set descricao = 'SUCRILHOS SEREAL - INSUMOS (KG)' where produto_id = 3476440;
update produto_planilha set descricao = 'TAMPA BOLHA POTE 360ML - INSUMO (UN)' where produto_id = 3836962;
update produto_planilha set descricao = 'TEMPURÁ - INSUMOS (KG)' where produto_id = 3485001;
update produto_planilha set descricao = 'TOMATE CEREJA - INSUMOS (KG)' where produto_id = 3476544;
update produto_planilha set descricao = 'TOMATE ITALIANO - INSUMOS (KG)' where produto_id = 3482196;
update produto_planilha set descricao = 'TOMATE LONGA VIDA - INSUMOS (KG)' where produto_id = 3476543;
update produto_planilha set descricao = 'TRIGO S/ FERMENTO - INSUMOS (KG)' where produto_id = 1857479;
update produto_planilha set descricao = 'UVA BLACK- INSUMOS (KG)' where produto_id = 1855914;
update produto_planilha set descricao = 'VARIEGATO DE MORANGO - INSUMO (KG)' where produto_id = 1855889;
update produto_planilha set descricao = 'VINAGRE BRANCO- INSUMOS (KG)' where produto_id = 3485002;
update produto_planilha set descricao = 'VINAGRE P/ SUSHI- INSUMOS (KG)' where produto_id = 3486121;
update produto_planilha set descricao = 'WASABI EM PÓ - INSUMOS (KG)' where produto_id = 3485004;
update produto_planilha set descricao = 'WASABI SACHÊ - INSUMOS (UN)' where produto_id = 3876739;
commit;
